article/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views, list_views

urlpatterns = [
    url(r'^article-column/$', views.article_column, name="article_column"),
    url(r'^rename-column/$', views.rename_article_column, name="rename_article_column"),
    url(r'^del-column/$', views.del_article_column, name="del_article_column"),
    url(r'^article-post/$', views.article_post, name="article_post"),
    url(r'^article-list/$', views.article_list, name="article_list"),
    url(r'^article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^del-article/$', views.del_article, name="del_article"),
    url(r'^redit-article/(?P<article_id>\d+)/$', views.redit_article, name="redit_article"),
    url(r'^list-article-titles/$', list_views.article_titles, name="article_titles"),
    url(r'^list-article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', list_views.article_detail, name="list_article_detail"),
    url(r'^list-article-titles/(?P<username>[-\w]+)/$', list_views.article_titles, name="author_articles"),
    url(r'^like-article/$', list_views.like_article, name="like_article"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

list/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.cert_list, name='cert_list'),
    url(r'(?P<result_id>\d+)/$', views.cert_result, name="cert_result"),
    url(r'search/$', views.search, name="search")
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^list/', include('list.urls', namespace='list', app_name='list')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^image/', include('image.urls', namespace='image', app_name='image')),
    url(r'^contract/', include('contract.urls', namespace='contract', app_name='contract')),
    url(r'^certvs/', include('certvs.urls', namespace='certvs', app_name='certvs')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column')
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name="article")
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name="article_column")
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)

    class Meta:
        #ordering = ("title",)
        ordering = ("-updated",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kargs)

    def get_absolute_url(self):
        return reverse("article:article_detail", args=[self.id, self.slug])

    def get_url_path(self):
        return reverse("article:list_article_detail", args=[self.id, self.slug])


class Comment(models.Model):
    article = models.ForeignKey(ArticlePost, related_name="comments")
    commentator = models.CharField(max_length=90)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

list/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin sqlcustom [app_label]'
# into your database.
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class CertificateTbl(models.Model):
    cert_id = models.AutoField(primary_key=True)
    cert_class = models.IntegerField()
    cert_name = models.CharField(max_length=20)
    cert_ename = models.CharField(max_length=50)
    cert_content = models.CharField(max_length=1000)
    cert_time = models.CharField(max_length=1000)
    cert_qualif = models.CharField(max_length=1000)
    cert_relate = models.CharField(max_length=1000, blank=True, null=True)
    cert_intro = models.CharField(max_length=1000)
    cert_link = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'certificate_tbl'

class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'django_migrations'

article/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import ArticleColumn,  ArticlePost, Comment


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = ArticleColumn
        fields = ("column",)

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ("title", "body")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

article/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from .models import ArticleColumn, ArticlePost
from .forms import ArticleColumnForm, ArticlePostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required(login_url='/account/login/')
@csrf_exempt
def article_column(request):
    if request.method == "GET":
        columns = ArticleColumn.objects.filter(user=request.user)
        column_form = ArticleColumnForm()
        return render(request, "article/column/article_column.html", {"columns":columns, 'column_form':column_form})

    if request.method == "POST":
        column_name = request.POST['column']
        columns = ArticleColumn.objects.filter(user_id=request.user.id, column=column_name)
        if columns:
            return HttpResponse('2')
        else:
            ArticleColumn.objects.create(user=request.user, column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def rename_article_column(request):
    column_name = request.POST["column_name"]
    column_id = request.POST['column_id']
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.column = column_name
        line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("0")


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article_column(request):
    column_id = request.POST["column_id"]
    try:
        line = ArticleColumn.objects.get(id=column_id)
        line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def article_post(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = request.user.article_column.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return HttpResponse("2")
        else:
            return HttpResponse("3")
    else:
        article_post_form = ArticlePostForm()
        article_columns = request.user.article_column.all()
        return render(request, "article/column/article_post.html",
                      {"article_post_form": article_post_form, "article_columns": article_columns})


@login_required(login_url='/account/login')
def article_list(request):
    #articles = ArticlePost.objects.filter(author=request.user)
    #return render(request, "article/column/article_list.html", {"articles":articles})
    articles_list = ArticlePost.objects.filter(author=request.user)
    paginator = Paginator(articles_list, 4)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request, "article/column/article_list.html", {"articles":articles, "page": current_page})


@login_required(login_url='/account/login')
def article_detail(request, id, slug):
    article = get_object_or_404(ArticlePost, id=id, slug=slug)
    return render(request, "article/column/article_detail.html", {"article":article})


@login_required(login_url='/account/login')
@require_POST
@csrf_exempt
def del_article(request):
    article_id = request.POST['article_id']
    try:
        article = ArticlePost.objects.get(id=article_id)
        article.delete()
        return HttpResponse("1")
    except:
    	return HttpResponse("2")


@login_required(login_url='/account/login')
@csrf_exempt
def redit_article(request, article_id):
    if request.method == "GET":
        article_columns = request.user.article_column.all()
        article = ArticlePost.objects.get(id=article_id)
        this_article_form = ArticlePostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request, "article/column/redit_article.html", {"article":article, "article_columns":article_columns, "this_article_column":this_article_column, "this_article_form":this_article_form})
    else:
        redit_article = ArticlePost.objects.get(id=article_id)
        try:
            redit_article.column = request.user.article_column.get(id=request.POST['column_id'])
            redit_article.title = request.POST['title']
            redit_article.body = request.POST['body']
            redit_article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")


def upload_file(request):
    if request.method == "POST":
        File = request.FILES.get("myfile", None)
        if File is None:
            return HttpResponse("no files for upload!")
        else:
            with open("static/tmp/%s" % File.name, 'wb+') as f:
                for chunk in File.chunks():
                    f.write(chunk)
            return HttpResponse("upload over!")
    else:
        return render(request, 'article/upload.html')

list/views.py
from django.shortcuts import render, get_object_or_404
from .models import CertificateTbl
from django.db.models import Q


def cert_list(request):
    lists = CertificateTbl.objects.all()
    return render(request, "list/list.html", {"lists": lists})

def cert_result(request, result_id):
    result = CertificateTbl.objects.get(cert_id=result_id)
    return render(request, "list/content.html", {"result":result})

def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = 'please enter what you want to check'
        return render(request, 'list/errors.html', {'error_msg': error_msg})
    result = CertificateTbl.objects.filter(Q(cert_name__contains=q) | Q(cert_ename__icontains=q)).first()
    if not result:
        return render(request, 'list/errors.html', {'error_msg': error_msg})
    return render(request, 'list/content.html', {'result': result})

templates/article/list/article_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}{{ article.title }}{% endblock %}
{% block content %}

{% with total_likes=article.users_like.count users_like=article.users_like.all %}

<div class="container">
    <header>
        <h1>{{ article.title }}</h1>
        <p>
            <a href="{% url 'article:author_articles' article.author.username %}">
                {{ article.author.username }}
            </a>
            <span><i class="lnr lnr-heart"></i>{{ total_likes }}like{{ total_likes | pluralize }}</span>
        </p>
    </header>

    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" />
    <div id='editormd-view'>
        <textarea id="append-test" style="display:none;">
{{ article.body }}
        </textarea>
    </div>
     <div>
        <p class="text-center">
            <a onclick="like_article({{article.id}}, 'like')" href="#"><i class="lnr lnr-thumbs-up"></i>like</a><span> &nbsp;</span>
            <a onclick="like_article({{article.id}}, 'unlike')" href="#"><i class="lnr lnr-thumbs-down"></i>unlike</a>
        </p>
    </div>
    <hr>
    <div>
        <h5><span class="glyphicon glyphicon-pencil"></span>本文有 {{ comments.count }} 评论</h5>
        {% for comment in article.comments.all %}
        <div>
            <p><strong>{{ comment.commentator }}</strong>说：</p>
            <p style="margin-left:40px;">{{ comment.body }}</p>
        </div>
        {% empty %}
        <p>没有评论</p>
        {% endfor %}

        <h5><span class="glyphicon glyphicon-pencil"></span>看文章，发评论，不要沉默</h5>
        <form action="." method="post" class="form-horizontal" role="form">{% csrf_token %}
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">评论员</label>
                <div class="col-sm-10">
                    {{ comment_form.commentator}}
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">评论</label>
                <div class="col-sm-10">
                    {{ comment_form.body }}
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <p><input type="submit" name="" value="发评论" class="btn btn-primary"></p>
                </div>
            </div>
        </form>
    </div>
</div>
<script src='{% static "js/jquery.js" %}'></script>
<script src='{% static "editor/lib/marked.min.js" %}'></script>
<script src='{% static "editor/lib/prettify.min.js" %}'></script>
<script src='{% static "editor/lib/raphael.min.js" %}'></script>
<script src='{% static "editor/lib/underscore.min.js" %}'></script>
<script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "editor/lib/flowchart.min.js" %}'></script>
<script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
<script src='{% static "editor/editormd.js" %}'></script>
<script type="text/javascript" src="{% static 'js/layer.js'%}"></script>
<script type="text/javascript">
$(function(){
	editormd.markdownToHTML("editormd-view", {
        htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
    });
});

function like_article(id,action){
    $.ajax({
        url: "{% url 'article:like_article' %}",
        type: "POST",
        data: {"id":id, "action":action},
        success: function(e){
            if(e=="1"){
                layer.msg("感谢点赞");
                window.location.reload();
            }else{
                layer.msg("我会继续努力");
                window.location.reload();
            }
        },
    });
}
</script>
{% endwith %}
{% endblock %}

templates/article/list/article_titles.html
{% extends "base.html" %}
{% block title %} articles {% endblock %}

{% block content %}
<div class="about-banner">
    <div class="container">
        <div class="about-main">
<div class="row text-center vertical-middle-sm">
    <h1 style="color:#777">Share our experience</h1>
</div>
<div class="container">
    {% for article in articles %}
     <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active">
            <h4 class="list-group-item-heading">{{article.title}}</h4>
        </a>
        <p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
        <p class="list-group-item-text">概要：{{article.body|slice:'70'| linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
</div>
</div>
</div>
{% endblock %}

templates/article/list/author_articles.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}articles{% endblock %}

{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>Share Your Experience</h1>
</div>
<div class="container">
<div class="col-md-8">
    {% for article in articles %}
    <div class="list-group">
        <a href="{{article.get_url_path}}" class="list-group-item active"><h4 class="list-group-item-heading">{{article.title}}</h4></a>
      	<p class="list-group-item-text">作者：<a href="{% url 'article:author_articles' article.author.username %}">{{article.author.username}}</a></p>
       	<p class="list-group-item-text">概要：{{article.body|slice:'70'|linebreaks}}</p>
    </div>
    {% endfor %}
{% include "paginator.html" %}
</div>
<div class="col-md-4">
<div>
     {% if userinfo.img %}
        <img src="{{ userinfo.img.url }}" width="200px" height="200px" class="img-circle"  name="user_face">
     {% else %}
        <img name="user_face" width="200px" src="{% static 'images/people.jpg' %}" class="img-circle" id="my_photo">
     {% endif %}
</div>
<div>
    <p>{{ user.username }}</p>
    {% if userinfo %}
    <p>{{ userinfo.school }}
    <p>{{ userinfo.aboutme }}</p>
{% else %}
<p>这个作者太懒了，什么也没有留下。</p>
{% endif %}
</div>
</div>
</div>
{% endblock %}