account/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='user_login'),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='user_logout'),
    url(r'^register/$', views.register, name='user_register'),
    url(r'^password-change/$', auth_views.password_change, {"post_change_redirect": "/account/password-change-done"}, name='password_change'),
    url(r'^password-change-done/$', auth_views.password_change_done, name='password_change_done'),
url(r'^password-reset/$', auth_views.password_reset,
        {"template_name":"account/password_reset_form.html",
         "email_template_name": "account/password_reset_email.html",
         "subject_template_name": "account/password_reset_subject.txt",
         "post_reset_redirect": "/account/password-reset-done"} , name='password_reset'),
    url(r'^password-reset-done/$', auth_views.password_reset_done, {"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name": "account/password_reset_confirm.html",
         "post_reset_redirect": "/account/password-reset-complete"} , name='password_reset_confirm'),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"},
        name='password_reset_complete'),
    url(r'^my-information/$', views.myself, name='my_information'),
    url(r'^edit-my-information/$',views.myself_edit, name='edit_my_information'),
    url(r'^edit-my-photo/$',views.uploadimg, name='uploadimg'),
    url(r'^special/$', views.special, name="special"),
    url(r'^vs/$', views.vs, name="vs"),
    url(r'^introduce/$', views.introduce, name="introduce"),
    url(r'^upload-file/$',views.upload_file, name='upload_file'),
    url(r'^show-file/$',views.show_file, name='show_file'),
    url(r'^download-file/$',views.download_file, name='download_file'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.blog_title, name="blog_title"),
    url(r'(?P<article_id>\d)/$', views.blog_article, name="blog_article"),
]

certvs/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'getvs/$', views.getvs, name="getvs")
]

image/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list-images/$', views.list_images, name="list_images"),
    url(r'^upload-image/$', views.upload_image, name='upload_image'),
    url(r'^del-image/$', views.del_image, name='del_image'),
    url(r'^images/$', views.falls_images, name="falls_images"),
]

list/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.cert_list, name='cert_list'),
    url(r'(?P<result_id>\d+)/$', views.cert_result, name="cert_result"),
    url(r'search/$', views.search, name="search")
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^list/', include('list.urls', namespace='list', app_name='list')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include("blog.urls", namespace="blog", app_name="blog")),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
    url(r'^image/', include('image.urls', namespace='image', app_name='image')),
    url(r'^contract/', include('contract.urls', namespace='contract', app_name='contract')),
    url(r'^certvs/', include('certvs.urls', namespace='certvs', app_name='certvs')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
     <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/layer.css' %}">
    <link rel="stylesheet" href="{% static 'css/linearicons/style.css' %}">
    <!--web-fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!--js-->
    <script src="{% static 'js/jquery.js'%}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- start-smoth-scrolling -->
    <script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/easing.js' %}"></script>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $(".scroll").click(function(event){
                event.preventDefault();
                $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
            });
        });
    </script>
    <!-- //end-smoth-scrolling -->
    <script src="{% static 'js/easyResponsiveTabs.js' %}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion
                width: 'auto', //auto or any width like 600px
                fit: true   // 100% fit in a container
            });
        });
    </script>
</head>
<body>
    {% include "header.html" %}
    <div>
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/base1.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<title>CertHelp Consulting</title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
	<link rel="stylesheet" href="{% static 'css/font-awesome/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/chartist-custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/layer.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
	<link rel="stylesheet" href="{% static 'css/demo.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/favicon.png' %}">
<body>
<div id="wrapper">
    {% include "header1.html" %}
    <div class="main">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer1.html" %}
    {% block javascript %}{% endblock %}
</div>
</body>
</html>

templates/footer.html
<div class="strip"> </div>
<div class="footer-h">
    <div class="container">
        <div class="footer-main">
            <div class="footer-left">
                <p class="data"> <a href="mailto:gallowsgogo@gmail.com"> gallowsgogo@ gmail.com. </a></p>
                <p> 2018 &copy Template by <a href="#"> Gallows </a></p>
            </div>
        </div>
    </div>
</div>
</body>

templates/footer1.html
<footer>
        <div class="container-fluid">
            <p> 2018 &copy Template by <a href="#"> Gallows </a></p>
        </div>
</footer>

templates/header.html
{% load staticfiles %}
<div class="header-b">
    <div class="container">
        <div class="header-main">
            <div class="logo">
                <a href="index.html"><img src="{% static 'images/cethelp_w.png' %}" alt=""></a>
            </div>
            <span class="menu"> <img src="{% static 'images/icon.png' %}"> </span>
            <div class="header-navg">
                <ul class="res">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'list:cert_list' %}">主 页</a></li>
                    <li><a href="{% url 'article:article_titles' %}">经验分享</a></li>
                    <li><a href="{% url 'image:falls_images' %}">晒证书</a></li>
                    <li><a href="{% url 'account:show_file' %}">试题下载</a></li>
                    <li><a href="{% url 'account:introduce' %}">我的空间</a></li>
                    <li><a href="{% url 'account:user_logout' %}">LOGOUT({{ user.username }})</a></li>
                    {% else %}
                    <li style="float:right"><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                    {% endif %}
                </ul>
                <script>
                    $( "span.menu").click(function() {
                        $(  "ul.res" ).slideToggle("slow", function() {
                            // Animation complete.
                        });
                    });
                </script>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

templates/header1.html
{% load staticfiles %}
    <!-- NAVBAR -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="brand">
            <a href="index.html"><img src="{% static 'images/cethelp.png' %}" alt="Klorofil Logo" class="img-responsive logo"></a>
        </div>
        <div class="container-fluid">
            <div class="navbar-btn">
                <button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
            </div>
            <form class="navbar-form navbar-left" method="get" action="/list/search/">
                <div class="input-group">
                    {% csrf_token %}
                    <input type="text" name="q" class="form-control" placeholder="证书名称 如：英语四级" required>
                    <span class="input-group-btn"><button class="btn btn-primary">Go</button></span>
                </div>
            </form>
            <div class="navbar-btn navbar-btn-right">
                <a class="btn btn-success update-pro" href="{% url 'list:cert_list' %}" title="Upgrade to Pro" ><span>GO BACK TO HOME</span></a>
            </div>
            <div id="navbar-menu">
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-rocket"></i> <span>反馈</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'contract:contract' %}">联系我们</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'images/user.png' %}" class="img-circle" alt="Avatar"> <span>{{ user.username }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}"><i class="lnr lnr-user"></i> <span>更改密码</span></a></li>
                            <li><a href="{% url 'account:user_logout' %}"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li style="float:right"><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- END NAVBAR -->
    <!-- LEFT SIDEBAR -->
    <div id="sidebar-nav" class="sidebar">
        <div class="sidebar-scroll">
            <nav>
                <ul class="nav">
                    <li><a href="{% url 'account:introduce' %}" class=""><i class="lnr lnr-home"></i> <span>系统说明</span></a></li>
                    <li>
                        <a href="#subPage" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>论坛管理</span><i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="subPage" class="collapse ">
                            <ul class="nav">
                                <li><a href="{% url 'article:article_column' %}" class="">栏目管理</a></li>
                                <li><a href="{% url 'article:article_post' %}" class="">文章发布</a></li>
                                <li><a href="{% url 'article:article_list' %}" class="">文章列表</a></li>
                            </ul>
                        </div>
                    </li>
                     <li><a href="{% url 'account:upload_file' %}" class=""><i class="lnr lnr-upload"></i> <span>试题上传</span></a></li>
                    <li><a href="{% url 'image:list_images' %}" class=""><i class="lnr lnr-chart-bars"></i> <span>证书图库</span></a></li>
                    <li>
                        <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>考证决策</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="subPages" class="collapse ">
                            <ul class="nav">
                                <li><a href="{% url 'certvs:getvs' %}" class="">VS决策</a></li>
                                <li><a href="{% url 'account:special' %}" class="">个性化决策</a></li>
                            </ul>
                        </div>
                    </li>
                    <li><a href="{% url 'account:my_information' %}" class=""><i class="lnr lnr-dice"></i> <span>个人信息</span></a></li>
                </ul>
            </nav>
        </div>
    </div>

templates/paginator.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>